sudo: false
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
python:
- 2.7
- pypy
install:
- .travis/install.sh
script:
- python -u setup.py clean
- CFLAGS="-O0 -g" python -u setup.py build_ext --inplace
- CFLAGS="-O0 -g" PYTHONUNBUFFERED=x make test
